# Generated by Django 6.1.1 on 2026-09-21 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting_type', models.CharField(choices=[('ANIMAL', 'Animal'), ('VEGETATION', 'Vegetation'), ('VIEWING', 'Viewing'), ('OTHER', 'Other')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('locationLongitude', models.FloatField()),
                ('locationLatitude', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animal_Sighting',
            fields=[
                ('sighting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.sighting')),
                ('common_name', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Sighting',
            fields=[
                ('sighting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.sighting')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Vegetation_Sighting',
            fields=[
                ('sighting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.sighting')),
                ('common_name', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
