# Generated by Django 6.1.1 on 2026-09-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='user',
            new_name='User',
        ),
    ]
