# Generated by Django 6.1.1 on 2026-09-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_sighting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='User',
            new_name='user',
        ),
    ]
