# Generated by Django 6.1.1 on 2026-09-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_sighting_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_Sighting',
            new_name='Sighting_Image',
        ),
    ]
