# Generated by Django 6.1.1 on 2026-10-03 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_image_sighting_sighting_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('region_type', models.CharField(blank=True, default='', max_length=100)),
                ('min_lat', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True)),
                ('min_lon', models.FloatField(blank=True, null=True)),
                ('max_lon', models.FloatField(blank=True, null=True)),
                ('elevation_ft', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=150, unique=True)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_game_species', models.BooleanField(default=False)),
                ('conservation_status', models.CharField(default='Least Concern', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sighting',
            name='animal_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sighting',
            name='behavior',
            field=models.CharField(blank=True, choices=[('FEEDING', 'Feeding'), ('RESTING', 'Resting'), ('MOVING', 'Moving'), ('DRINKING', 'Drinking'), ('HUNTING', 'Hunting'), ('CALLING', 'Calling'), ('NESTING', 'Nesting'), ('MATING', 'Rutting/Mating'), ('FLEEING', 'Fleeing'), ('OTHER', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sighting',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sighting',
            name='observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='temperature_f',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='animal_sighting',
            name='sighting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='animal_sighting', serialize=False, to='api.sighting'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sighting_image',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sighting_image',
            name='sighting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='legacy_image', serialize=False, to='api.sighting'),
        ),
        migrations.AlterField(
            model_name='vegetation_sighting',
            name='sighting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vegetation_sighting', serialize=False, to='api.sighting'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.sighting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sighting_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sighting',
            name='habitat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sightings', to='api.habitat'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sightings', to='api.region'),
        ),
        migrations.CreateModel(
            name='SightingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.sighting')),
            ],
        ),
        migrations.CreateModel(
            name='HuntingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('weapon', models.CharField(blank=True, default='', max_length=100)),
                ('open_month_day', models.CharField(max_length=5)),
                ('close_month_day', models.CharField(max_length=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_seasons', to='api.species')),
            ],
        ),
        migrations.AddField(
            model_name='animal_sighting',
            name='species_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animal_sightings', to='api.species'),
        ),
        migrations.AddField(
            model_name='species',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species', to='api.speciescategory'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sightings', to='api.weathercondition'),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(-1, 'Dispute'), (1, 'Confirm')])),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='api.sighting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sighting_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sighting', 'user'), name='unique_sighting_verification')],
            },
        ),
    ]
